Aggiunto appunti
unipr-org/LIeC pull request #16
Opened 2024-11-16 09:18 UTC by ariannacipolla

Aggiunto appunti 03-analisi-sintattica.md e 04-analisi-semantica.md

2024-11-16 11:30 UTC, merendamattia requested changes

2024-11-16 11:30 UTC, merendamattia commented on teoria/02-analisi-lessicale.md
> +![[NFA.jpeg|center|500]]
rimuovi center 500, non e' compatibile per l'esportazione con le github action

2024-11-16 11:30 UTC, merendamattia commented on teoria/04-analisi-semantica.md
> +![[binarysign_grammar.png | center | 300]]
anche qui rimuovi center e numero

2024-11-16 11:30 UTC, merendamattia commented on teoria/04-analisi-semantica.md
> +![[ast_signbinary.png | center | 550]]
anche qui rimuovi center e numero

2024-11-16 11:30 UTC, merendamattia commented on teoria/04-analisi-semantica.md
> +![[attribute_signbinary.png| left |400]] ![[result_signbinary.png|right|220]]
anche qui rimuovi center e numero

2024-11-16 11:30 UTC, merendamattia commented on teoria/04-analisi-semantica.md
> + ![[AST_attribute.jpeg | center | 450]]
anche qui rimuovi center e numero

2024-11-16 16:44 UTC, merendamattia approved these changes

2024-11-17 13:29 UTC, manueldiagostino approved these changes

2024-11-17 13:29 UTC, merged